name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Check SSH variables
        run: |
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"

      - name: Debug GitHub Actions IP
        run: |
          echo "GitHub Actions IP: $(curl -s ifconfig.me)"

      - name: Deploy over SSH
        run: |
          ssh -vvv -tt -oHostKeyAlgorithms=+ssh-ed25519 -oKexAlgorithms=+curve25519-sha256 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            cd ~/apps/nextjs-app || exit
            echo "Pulling latest changes..."
            git fetch origin
            git reset --hard origin/master
            echo "Current commit: $(git log -1 --oneline)"
            echo "Installing dependencies..."
            npm install
            echo "Building application..."
            npm run build
            echo "Restarting PM2..."
            pm2 delete nextjs-app || true
            pm2 start npm --name "nextjs-app" -- start
            pm2 save
            echo "Deployment complete!"
          EOF